// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBJ7Wc91G2goeVtsfqf5X9yF8WOTVKnrM',
    appId: '1:540041693797:web:8972fb1944824d76c9148c',
    messagingSenderId: '540041693797',
    projectId: 'dipity-716b0',
    authDomain: 'dipity-716b0.firebaseapp.com',
    databaseURL: 'https://dipity-716b0-default-rtdb.firebaseio.com',
    storageBucket: 'dipity-716b0.appspot.com',
    measurementId: 'G-9CM74T5R8Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlZS-NA5nZwKOCVuFf3oMA-sxDBvfG5YY',
    appId: '1:540041693797:android:23326325d3ed41abc9148c',
    messagingSenderId: '540041693797',
    projectId: 'dipity-716b0',
    databaseURL: 'https://dipity-716b0-default-rtdb.firebaseio.com',
    storageBucket: 'dipity-716b0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAn79uqaMpt7CVymxD7PXIQrGXnqX2bSBI',
    appId: '1:540041693797:ios:57d0b2958873d027c9148c',
    messagingSenderId: '540041693797',
    projectId: 'dipity-716b0',
    databaseURL: 'https://dipity-716b0-default-rtdb.firebaseio.com',
    storageBucket: 'dipity-716b0.appspot.com',
    iosClientId: '540041693797-a2n4r7pcags8p60i7r3ucbi4m5mh3hur.apps.googleusercontent.com',
    iosBundleId: 'com.onatcipli.dipity',
  );
}
